<?php
// $Id: quicktabrotate.module,v 1.1.2.1 2009/06/01 11:11:30 grndlvl Exp $
/**
 * @file
 * Integration with the views module to create the new embed views display.
 */

/**
 * Implementation of hook_views_plugins
 */
function quicktabrotate_preprocess(&$vars){
if ($vars['is_front']) {
$modulepath = drupal_get_path('module','quicktabrotate');
drupal_add_js($modulepath.'/future_quicktabs_rotate.js');
}
}